# Generated by Django 5.0 on 2023-12-26 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoproject',
            name='status',
            field=models.CharField(choices=[('Done', 'Done'), ('In progress', 'In progress'), ('Not done', 'Not done')], max_length=50),
        ),
    ]
