# Generated by Django 5.0.1 on 2024-01-29 16:10

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_brand_brand_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='brand_slug',
            field=autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='brand_name', unique=True),
        ),
        migrations.AddField(
            model_name='category',
            name='category_slug',
            field=autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='category_name', unique=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_slug',
            field=autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='product_name', unique=True),
        ),
    ]
