# Generated by Django 5.0.1 on 2024-02-06 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='number',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
    ]
