# Generated by Django 5.0.2 on 2024-02-27 07:56

import autoslug.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('customer_name', models.CharField(max_length=100)),
                ('locality', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('zipcode', models.PositiveIntegerField()),
                ('zone', models.CharField(choices=[('Mahakali', 'Mahakali'), ('Seti', 'Seti'), ('Bheri', 'Bheri'), ('Karnali', 'Karnali'), ('Rapti', 'Rapti'), ('Dhawalagiri', 'Dhawalagiri'), ('Lumbini', 'Lumbini'), ('Gandaki', 'Gandaki'), ('Bagmati', 'Bagmati'), ('Narayani', 'Narayani'), ('Janakpur', 'Janakpur'), ('Sagarmatha', 'Sagarmatha'), ('Koshi', 'Koshi'), ('Mechi', 'Mechi')], max_length=100)),
                ('number', models.CharField(max_length=15)),
                ('customer_slug', autoslug.fields.AutoSlugField(blank=True, editable=False, null=True, populate_from='customer_name', unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
